apiVersion: v1
kind: Service
metadata:
  name: <>
  namespace: <>
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    <>: <>
  sessionAffinity: None
  type: ClusterIP
